workflows:
    version: 2
    build-deploy:
      jobs:
        - build

  
  version: 2
  jobs:
    build:
      docker:
        - image: circleci/python:3.6.2-stretch-browsers
          environment:
            DATABASE_URL: postgresql://myUsr:somePwd@localhost:5432/myUsr
        - image: circleci/postgres:9.6.5-alpine-ram

      steps:
        - checkout
        - restore_cache:
            key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
        - run:
            name: Install Python deps in a venv
            command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements/dev.txt
        - save_cache:
            key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
            paths:
              - "venv"

        - run;
            command: |
              . venv/bin/activate
              sleep 1
              flask db upgrade
        - run:
            command: |
              . venv/bin/activate
              flask test
        - store_artifacts:
            path: test-reports/
            destination: tr1
        - store_test_results:
            path: test-reports/
#    deploy:
 #     steps:
  #      - checkout
   #     - run:
    #        name: Deploy Master to Heroku
     #       command: |
      #        git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master