version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        environment:
          DATABASE_URL: postgresql://myUsr:somePwd@localhost:5432/myUsr
      - image: circleci/postgres:9.6.5-alpine-ram
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt

          environment:
            CONDUIT_SECRET: something-really-secret
            FLASK_APP: /home/circleci/repo/autoapp.py
            FLASK_DEBUG: 1
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - "venv"

      - run:
          command: |
            . venv/bin/activate
            flask db upgrade
          environment:
            CONDUIT_SECRET: something-really-secret
            FLASK_APP: /home/circleci/repo/autoapp.py
            FLASK_DEBUG: 1
      - run:
          command: |
            . venv/bin/activate
            flask test

          environment:
            CONDUIT_SECRET: something-really-secret
            FLASK_APP: /home/circleci/repo/autoapp.py
            FLASK_DEBUG: 1  
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
